# Connection info for Windows hosts
ansible_user: Administrator
ansible_password: "QzX-mLFTJNKw-hVu(O0Ueq7of?hCg!Hh"
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_port: 5985
ansible_winrm_server_cert_validation: ignore

# Application variables
env_name: "DEV"
deploy_date: "{{ ansible_date_time.date }}"
api_key: "123456789"

# Optional: web server variables
nginx_port: 8080
nginx_path: "C:\\inetpub\\wwwroot"

