$ANSIBLE_VAULT;1.1;AES256
30333862396565653631383566393737396466303239393134383231383036646338333031653662
3761303963303634616437356334383237306439613262390a633062656435343434663332663431
39383536326430363335353565636530663264386136323462333935636330653637353032373931
6366643635363565610a363164653061613334396366333861306531373863386136353064643935
66353032636262643266653639396135653066643765353366323239353661306435373039326666
37333366626663303837626661613036353832356439653935313463653961636661353633663231
35316133636666623734343162346166323066323230616464316661626332616438376237306263
35363538663335306165353139366465666562306634376162313731343334653865633465303462
3439
