$ANSIBLE_VAULT;1.1;AES256
64663238363865376537353766326238633032336334346666663730316633346534646536643236
3435396664373730663737303030616331663561306537350a333034343833313761613766613633
33353337663033633061666138666266393566663662343366396162326463303364363535363364
3362316431346539390a326236663433643536366435616636393261303738616263636564633236
61356635613961666366376666656431316338343266616137343762356263323463306666656362
6363626265393437343666626663303461366634366230343162
